### ISSUE TITLE
VCS Enhancements 

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/vcs#740]
- [x] Remove EDV dependencies #734 
- [x] Remove Governance Framework Dependency #736
- [x] Remove Uniregistrar dependency while creating profiles #736
- [x] Remove unused/unwanted packages #736 
- [x] Improve linters #742 
- [x] Optimize DBs #735 
- [x] Generate Open API Spec 
  - use latest, all request response parameters annotated and cover all endpoints #737
